---
name: macOS

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: CMake v3.${{ matrix.cmake_version }}
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        cmake_version: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]

    steps:

    - name: ðŸ“¥ Checkout
      uses: actions/checkout@v3

    - name: ðŸ“‚ Load .env file
      if: hashFiles('.github/workflows/.env') != ''
      uses: xom9ikk/dotenv@v2
      with:
        path: .github/workflows

    - name: â¬‡ï¸ Setup CMake
      uses: lukka/get-cmake@latest
      if: ${{ matrix.cmake_version >=2 && matrix.cmake_version <=6 }}
      with:
        cmakeVersion: ~3.${{ matrix.cmake_version }}
        ninjaVersion: ^1.11.1

    - name: â¬‡ï¸ Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.13
      if: ${{ matrix.cmake_version <2 || matrix.cmake_version >6 }}
      with:
        cmake-version: 3.${{ matrix.cmake_version }}.x
        github-api-token: ${{ secrets.GITHUB_TOKEN }}

    - name: ðŸ”§ Generate with v3.${{ matrix.cmake_version }}
      if: ${{ matrix.cmake_version < 13 }}
      run: cmake -E make_directory ${{ env.CMAKE_BINARY_PREFIX }}; cmake -E chdir ${{ env.CMAKE_BINARY_PREFIX }} cmake -G "Ninja" -Werror=dev -Werror=deprecated -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }}  ${{ github.workspace }}/${{ env.CMAKE_SOURCE_PREFIX
        }}

    - name: ðŸ”§ Generate with v3.${{ matrix.cmake_version }}
      if: ${{ matrix.cmake_version >= 13 &&  matrix.cmake_version < 17 }}
      run: cmake -S ${{ env.CMAKE_SOURCE_PREFIX }} -B ${{ env.CMAKE_BINARY_PREFIX }} -G "Ninja" -Werror=dev -Werror=deprecated -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }}

    - name: ðŸ”§ Generate with v3.${{ matrix.cmake_version }}
      if: ${{ matrix.cmake_version >= 17 }}
      run: cmake -S ${{ env.CMAKE_SOURCE_PREFIX }} -B ${{ env.CMAKE_BINARY_PREFIX }} -G "Ninja Multi-Config" -Werror=dev -Werror=deprecated
